### ISSUE TITLE
Documentation: Copy Resources module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CopyResources#2]
See #1 for module features

**Comment by allanaaa** [comment]
I have some placeholders in here for the module versions that will be compatible with this. 

I also haven't put anything in here about resources being private by default, though I'm hoping you'll make that happen before release.

Otherwise, I think this is reasonably complete. I have a little "issues" section for copying sites, since that's most complicated, to which we can add anything you think useful. 

Can you particularly review the Permissions section and make sure I got all that right?

**Comment by jimsafley** [comment]
We've decided to give users the option to set visibility when copying resources. See #3. The default is "Same as original" given that's what people expect. But they will have the opportunity to set resource to private without having to edit the copied resource, set the visibility to private, and save the form.

**Comment by jimsafley** [comment]
The permissions section is accurate.

**Comment by allanaaa** [comment]
This is ready to be published, except for getting the correct module versions into the requirements section. I guessed at what I put in there but it needs to be double-checked before release. 

I'll keep it in draft for that reason, but we're otherwise ready, depending on your answer to https://github.com/omeka-s-modules/CopyResources/issues/4.
